In [1]:
import pandas as pd

In [2]:
sf = pd.read_csv('spike_forensics.csv', dtype={'period': str})

print(sf.shape)
print(sf.dtypes)
display(sf.head())

(853, 5)
period          object
window_group    object
event_name      object
n_events         int64
n_users          int64
dtype: object

     period window_group           event_name  n_events  n_users
0  20180628   pre_window        session_start      1113      730
1  20180628   pre_window      user_engagement     19919      779
2  20180628   pre_window           post_score      2410      331
3  20180628   pre_window            level_end       761      107
4  20180628   pre_window  level_end_quickplay      5751      560

In [3]:
spike_dates = ['20180618', '20180619', '20180625', '20180626', '20180628', '20180630', '20180701']
interleaved_dates = ['20180620', '20180621', '20180622', '20180623', '20180624', '20180627', '20180629']

label_map = {}

for date in spike_dates:
    label_map[date] = 'spike'

for date in interleaved_dates:
    label_map[date] = 'interleaved'

label_map['stable_block'] = 'anchor'

sf['label'] = sf['period'].map(label_map)

sf

,period,window_group,event_name,n_events,n_users,label
0,20180628,pre_window,session_start,1113,730,spike
1,20180628,pre_window,user_engagement,19919,779,spike
2,20180628,pre_window,post_score,2410,331,spike
3,20180628,pre_window,level_end,761,107,spike
4,20180628,pre_window,level_end_quickplay,5751,560,spike
...,...,...,...,...,...,...
848,stable_block,pre_window,notification_foreground,1,1,anchor
849,stable_block,in_window,dynamic_link_app_open,13,6,anchor
850,stable_block,in_window,challenge_accepted,3,2,anchor
851,stable_block,pre_window,dynamic_link_app_open,3,2,anchor
852,stable_block,pre_window,in_app_purchase,5,5,anchor

In [4]:
print(sf['label'].isna().sum())


sf.groupby('label')['period'].nunique()

0

label
anchor         1
interleaved    7
spike          7
Name: period, dtype: int64

In [5]:
pre_window = sf[sf['window_group'] == 'pre_window']

grouped_by_label_event = pre_window.groupby(['label', 'event_name'])['n_events'].sum().reset_index()
grouped_by_label_event['total'] = grouped_by_label_event.groupby('label')['n_events'].transform('sum')
grouped_by_label_event['share'] = grouped_by_label_event['n_events'] / grouped_by_label_event['total']

pivoted = grouped_by_label_event.pivot_table(index='event_name', columns='label', values='share')
pivoted.sort_values('spike', ascending=False)

label                           anchor  interleaved     spike
event_name
user_engagement           2.243122e-01     0.228853  0.394687
level_start_quickplay     9.743128e-02     0.095897  0.165786
level_end_quickplay       6.466267e-02     0.063530  0.115223
screen_view               4.193910e-01     0.417086  0.061335
post_score                4.346699e-02     0.041599  0.057895
level_fail_quickplay      2.411953e-02     0.025910  0.046327
level_reset_quickplay     2.344017e-02     0.021132  0.035571
level_start               5.719341e-03     0.007858  0.022215
session_start             1.299960e-02     0.011337  0.020994
level_end                 4.174712e-03     0.005498  0.016701
level_retry               3.144023e-03     0.004759  0.011476
level_retry_quickplay     5.067507e-03     0.004827  0.010665
level_complete            2.760674e-03     0.003643  0.007323
level_up                  2.926651e-03     0.003976  0.007189
level_complete_quickplay  4.053922e-02     0.037626  0.007020
level_fail                1.248341e-03     0.001522  0.005285
select_content            1.815164e-02     0.019689  0.004251
level_reset               5.178721e-04     0.000871  0.002445
use_extra_steps           1.162685e-03     0.000638  0.001563
os_update                 5.847124e-04     0.000514  0.001346
app_update                4.765883e-04     0.000340  0.000879
app_exception             1.011592e-03     0.000776  0.000802
ad_reward                 3.010623e-04     0.000183  0.000763
no_more_extra_steps       3.563881e-04     0.000216  0.000731
app_remove                2.022060e-04     0.000360  0.000639
completed_5_levels        1.390166e-04     0.000167  0.000398
firebase_campaign         9.660954e-05     0.000065  0.000303
challenge_a_friend        5.476413e-05     0.000092  0.000101
spend_virtual_currency    1.234861e-03     0.000805  0.000045
in_app_purchase           1.404208e-06     0.000003  0.000012
app_clear_data            1.685050e-06     0.000007  0.000009
dynamic_link_first_open            NaN          NaN  0.000009
error                     3.016240e-04     0.000223  0.000009
dynamic_link_app_open     8.425250e-07          NaN  0.000006
challenge_accepted        2.808417e-07          NaN       NaN
notification_foreground   2.808417e-07          NaN       NaN